### PR TITLE
Make impossible possible

### PR DESCRIPTION
**Pull request by szepeviktor**
John's favorite number is 478!

From https://github.com/johnbillion/wp_mail/pull/35#issuecomment-1682323638

# 🎁

image

### CODE REVIEW

**Comment by johnbillion** [comment]
I thought you were a purist Viktor

**Comment by szepeviktor** [comment]
Does it mean a go or a no-go?

**Comment by johnbillion** [comment]
I don't think I'll bother with this. It doesn't make things more readable like I thought it would. Thanks anyway!

**Comment by szepeviktor** [comment]
# 🫠

**Comment by szepeviktor** [comment]
I am just a 🤖 robot. I do as you say.

**Pull request closed without merging**
